// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RiskApi.Data;

#nullable disable

namespace RiskApi.Migrations
{
    [DbContext(typeof(RiskDbContext))]
    [Migration("20260119235520_AddTreatmentAndReports")]
    partial class AddTreatmentAndReports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RiskApi.Models.Asset", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetValue")
                        .HasColumnType("int");

                    b.Property<int>("Availability")
                        .HasColumnType("int");

                    b.Property<int>("Confidentiality")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Integrity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("RiskApi.Models.Control27002", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Controls");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "5.1",
                            Description = "Define and maintain information security policies.",
                            Name = "Policies for information security",
                            Type = "Organizational"
                        },
                        new
                        {
                            Id = 2,
                            Code = "5.15",
                            Description = "Control access to information and systems.",
                            Name = "Access control",
                            Type = "Technological"
                        },
                        new
                        {
                            Id = 3,
                            Code = "8.9",
                            Description = "Manage secure configurations for systems and services.",
                            Name = "Configuration management",
                            Type = "Technological"
                        },
                        new
                        {
                            Id = 4,
                            Code = "8.16",
                            Description = "Log and monitor security events.",
                            Name = "Monitoring activities",
                            Type = "Technological"
                        },
                        new
                        {
                            Id = 5,
                            Code = "8.12",
                            Description = "Prevent unauthorized data exfiltration.",
                            Name = "Data leakage prevention",
                            Type = "Technological"
                        });
                });

            modelBuilder.Entity("RiskApi.Models.Risk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("ExistingControls")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Impact")
                        .HasColumnType("int");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Observations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Probability")
                        .HasColumnType("int");

                    b.Property<string>("Recommendations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResidualImpact")
                        .HasColumnType("int");

                    b.Property<string>("ResidualLevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResidualProbability")
                        .HasColumnType("int");

                    b.Property<int?>("ResidualScore")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Threat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Vulnerability")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.ToTable("Risks");
                });

            modelBuilder.Entity("RiskApi.Models.TreatmentControl", b =>
                {
                    b.Property<int>("TreatmentPlanId")
                        .HasColumnType("int");

                    b.Property<int>("Control27002Id")
                        .HasColumnType("int");

                    b.Property<string>("Evidence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ImplementedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TreatmentPlanId", "Control27002Id");

                    b.HasIndex("Control27002Id");

                    b.ToTable("TreatmentControls");
                });

            modelBuilder.Entity("RiskApi.Models.TreatmentPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RiskId")
                        .HasColumnType("int");

                    b.Property<string>("Strategy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RiskId")
                        .IsUnique();

                    b.ToTable("TreatmentPlans");
                });

            modelBuilder.Entity("RiskApi.Models.Risk", b =>
                {
                    b.HasOne("RiskApi.Models.Asset", "Asset")
                        .WithMany("Risks")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");
                });

            modelBuilder.Entity("RiskApi.Models.TreatmentControl", b =>
                {
                    b.HasOne("RiskApi.Models.Control27002", "Control")
                        .WithMany()
                        .HasForeignKey("Control27002Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RiskApi.Models.TreatmentPlan", "TreatmentPlan")
                        .WithMany("TreatmentControls")
                        .HasForeignKey("TreatmentPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Control");

                    b.Navigation("TreatmentPlan");
                });

            modelBuilder.Entity("RiskApi.Models.TreatmentPlan", b =>
                {
                    b.HasOne("RiskApi.Models.Risk", "Risk")
                        .WithOne("TreatmentPlan")
                        .HasForeignKey("RiskApi.Models.TreatmentPlan", "RiskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Risk");
                });

            modelBuilder.Entity("RiskApi.Models.Asset", b =>
                {
                    b.Navigation("Risks");
                });

            modelBuilder.Entity("RiskApi.Models.Risk", b =>
                {
                    b.Navigation("TreatmentPlan");
                });

            modelBuilder.Entity("RiskApi.Models.TreatmentPlan", b =>
                {
                    b.Navigation("TreatmentControls");
                });
#pragma warning restore 612, 618
        }
    }
}
